version: '3.8'

services:
  db:
    image: postgres:14.3
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=Baha
      - POSTGRES_PASSWORD=BaHa1206
      - POSTGRES_DB=Motivator
    ports:
      - 5432:5432

  app:
    container_name: motivator_users
    build: .
    command: sh -c "python motivator/manage.py migrate && python motivator/manage.py runserver 0.0.0.0:8000"

    depends_on:
      - db
      
    volumes:
      - ./motivator:/motivator_users

    ports:
      - 8000:8000

volumes:
  postgres_data:
  motivator:
